name: "elderly_system"
mode: "release"
port: 8080
start_time: "2023-03-01"
machine_id: 1

log:
  level: "debug"
  filename: "elderly_system.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: mysql57
  port: 3306
  user: "root"
  password: "123456"
  dbname: "RaspberryPi"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: redis507
  port: 6379
  password: ""
  db: 1
  pool_size: 100
